### ISSUE TITLE
Control Flow statements

### ISSUE THREAD

**Issue by TomasaMuller** [nralbrecht/graphic-canvas#1]
Hello,
In your readme you have planned a todo list one of which is implementing control flow statements

> Add control flow elements (if, while, for, ...)

Can you provide some hints about how to implement these?

**Comment by nralbrecht** [comment]
Hello, sorry for the delayed response.

I believe I followed the excellent ["Crafting Interpreters" E-Book from Robert Nystrom](https://craftinginterpreters.com/). You will find the interpreter in the [VM directory](https://github.com/nralbrecht/graphic-canvas/tree/master/GraphicCanvas/VM). If I remember correctly, I implemented a stack based bytecode interpreter. Have a look at his guide to implement jumps: https://craftinginterpreters.com/jumping-back-and-forth.html.
